export const DEPARTMENTS = [
    'Application Development',
    'Artificial Intelligence',
    'Back-end Engineering',
    'Business Systems',
    'Cloud Infrastructure',
    'Cloud Operations',
    'Cybersecurity',
    'Data Analytics',
    'Data Engineering',
    'Data Science',
    'Database Administration',
    'Desktop Support',
    'DevOps',
    'Digital Transformation',
    'Enterprise Architecture',
    'Front-end Engineering',
    'Governance & Risk',
    'Help Desk',
    'Information Security',
    'Infrastructure',
    'IT Operations',
    'IT Procurement',
    'IT Project Management',
    'Mobile App Development',
    'Network Engineering',
    'Network Operations Center',
    'Product Management',
    'Quality Assurance',
    'Release Management',
    'SaaS Management',
    'Site Reliability Engineering',
    'Software Development',
    'Software Engineering',
    'Systems Administration',
    'Systems Integration',
    'Technical Support',
    'Technical Writing',
    'UI/UX Design',
    'Web Development',
    'Wireless Communications',
]
